mybatis:
  mapper-locations: classpath*:mapper/*.xml
  config-locations: classpath:mybatis-config.xml
  type-aliases-package: com.ky.jyg.**.pojo
#===================== 分页插件 ============================
pagehelper:
  helper-dialect: mysql  #分页插件方言选择
  params: count=countSql  
  reasonable: true  #合理化参数，设为true时pageNum<=0 时会查第一页， pageNum>pages（超过总数时），会查询最后一页
  support-methods-arguments: true
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-active: 20
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-idle: 5
      pool-prepared-statements: true
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      db-type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/hospital?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8&rewriteBatchedStatements=true
      username: root
      password: root
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 30000